// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return web;
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmSUrWIwbLAEP0gF8Ci9un9RVkOhY7DL4',
    authDomain: 'smartrelief-a9b54.firebaseapp.com',
    projectId: 'smartrelief-a9b54',
    storageBucket: 'smartrelief-a9b54.firebasestorage.app',
    messagingSenderId: '127143907466',
    appId: '1:127143907466:web:9576ce51a4f02d85f11d73',
    measurementId: 'G-QC2FB4ENCC',
  );
}
